# This file generates the GitHub Actions matrix for ZMK firmware builds

include:
  - board: nice_nano
    shield: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corne_left

  - board: nice_nano
    shield: corne_right
    artifact-name: corne_right
