# This file generates the GitHub Actions matrix for ZMK firmware builds

include:
  - board: nice_nano_v2
    shield: corne_left
    artifact-name: corne_left

  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne_right
